### ISSUE TITLE
Query regarding BinaryAI website

### ISSUE THREAD

**Issue by Bogdan-github** [binaryai/plugins#3]
Hi,
I am trying to use `BinaryAI` for comparison purposes to be used as a baseline for my experiments. Currently, I am able to upload a single binary and download the corresponding json from [https://www.binaryai.net/](https://www.binaryai.net/) but I would require this functionality for a bunch of binaries, is there some public API or workaround available which can be used for this purpose?

**Comment by michellehong** [comment]
We cannot guarantee stability and compatibility of the GraphQL API and therefore we do not offer an API doc at this time. However, we do not intend to restrict acceptable use of the API. Please note that some features in GraphQL may still be buggy and we may fix them later, but we cannot make any promises at this time. 
Thank you for your interest in BinaryAI.😊

**Comment by Bogdan-github** [comment]
Thank you for the reply.
